#****************Eureka单机配置****************
server:
  port: 1000
  servlet.context-path: /@project.artifactId@

spring:
  application:
    name: @project.artifactId@
  #SpringBoot引入其他公共的配置信息
  profiles:
    include: public

#****************Eureka配置****************
eureka:
  client:
    #是否从Eureka Server获取注册信息，默认true。当前是单一节点的Eureka Server，不需要同步其他Eureka Server节点的数据，设为false。
    fetch-registry: false
    #是否将自己注册到Eureka Server，默认true。当前应用是Eureka Server，设为false。
    register-with-eureka: false
    #与Eureka Server交互的地址，查询服务和注册服务都依赖这个地址，默认:http://localhost:8761/eureka/，多个地址用 , 分隔。
    service-url:
      defaultZone: http://localhost:${server.port}${server.servlet.context-path}/eureka/
  instance:
    #是否将自己的 IP 注册到 Eureka Server(默认 false,表示注册微服务所在操作系统的 hostname 到Eureka Server)
    prefer-ip-address: true
    appname: ${spring.application.name}
    home-page-url-path: /${server.servlet.context-path}
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    #Eureka可以自定义key-value的元数据
    metadata-map:
      service-function: 这是一个Eureka单机注册中心
