CREATE TABLE `ord_user_order` (
  `USER_ORDER_ID` bigint NOT NULL COMMENT '主键',
  `ORDER_ID` bigint NOT NULL COMMENT '订单ID',
  `ORDER_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单类型',
  `BIZ_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单系统',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '下单时间',
  `USER_ID` bigint DEFAULT NULL COMMENT '下单人',
  `DELETE_FLAG` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '删除标记（Y:已删除，N/NULL:未删除）',
  PRIMARY KEY (`USER_ORDER_ID`),
  KEY `IDX_ORD_USER_OID` (`ORDER_ID`),
  KEY `IDX_ORD_USER_OID_UID` (`ORDER_ID`,`USER_ID`),
  KEY `IDX_ORD_USER_OUID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;