#****************SpringBoot服务端口****************
server:
  port: 3000

spring:
  profiles:
    #SpringBoot引入其他公共的配置信息
    include: public

#****************接口服务地址配置****************
service:
  url1: http://localhost:2000/provider-eureka-no
