#****************Eureka集群配置****************
server:
  port: 1000
  servlet.context-path: /@project.artifactId@

spring:
  application:
    name: @project.artifactId@
  #SpringBoot引入其他公共的配置信息
  profiles:
    include: public

#****************Eureka配置****************
spring.cloud.config.discovery.enabled: true
eureka:
  instance:
    #是否将自己的 IP 注册到 Eureka Server(默认 false,表示注册微服务所在操作系统的 hostname 到Eureka Server)
    prefer-ip-address: true
    appname: ${spring.application.name}
    home-page-url-path: /${server.servlet.context-path}
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    #Eureka可以自定义key-value的元数据
    metadata-map:
      service-function: 这是一个Eureka注册中心集群

#****************Eureka互相注册地址配置****************
eureka-service-url-1: http://localhost:1002${server.servlet.context-path}/eureka/,http://localhost:1003${server.servlet.context-path}/eureka/
eureka-service-url-2: http://localhost:1001${server.servlet.context-path}/eureka/,http://localhost:1003${server.servlet.context-path}/eureka/
eureka-service-url-3: http://localhost:1001${server.servlet.context-path}/eureka/,http://localhost:1002${server.servlet.context-path}/eureka/

#****************Eureka集群node配置****************
---  ## Eureka Server 1
spring:
  profiles: node1
server:
  port: 1001
eureka:
  instance:
    hostname: node1
  client:
    service-url:
      defaultZone: ${eureka-service-url-1}

---  ## Eureka Server 2
spring:
  profiles: node2
server:
  port: 1002
eureka:
  instance:
    hostname: node2
  client:
    service-url:
      defaultZone: ${eureka-service-url-2}

---  ## Eureka Server 3
spring:
  profiles: node3
server:
  port: 1003
eureka:
  instance:
    hostname: node3
  client:
    service-url:
      defaultZone: ${eureka-service-url-3}
