## 单机配置 context-path
server:
  servlet.context-path: /eureka-base
  port: 1000

spring:
  application:
    name: eureka-base

## eureka配置
spring.cloud.config.discovery.enabled: true
eureka:
  instance:
    hostname: eureka1
  client:
    #是否从 Eureka Server 获取本实例的注册信息(默认true,当前是单个节点设为false)
    fetch-registry: false
    #是否将本实例注册到Eureka Server(默认true,当前应用是Eureka Server设为false)
    register-with-eureka: false
    #与Eureka Server交互的地址，查询服务和注册服务都依赖这个地址(默认: http://localhost:8761/eureka/ ,多个地址用 , 分隔)
    service-url:
      defaultZone: http://127.0.0.1:${server.port}${server.servlet.context-path}/eureka/



